# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/tkmgo/haproxyconfigparser
    steps:
      - checkout
      - run: go test -v ./... -bench .

      - run: go build -o haproxy-cfg2json cmd/haproxy-cfg2json/main.go
      - store_artifacts:
          path: haproxy-cfg2json
